version: '3'
services:
  store-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./app:/usr/src/app

#docker-compose run [app_name] django-admin startproject myproject .